### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by mateoconlechuga** [fbdajh/Calculatormon-CE#4]
ERROR (217) Cannot open include file "gfx/test_gfx.h"

Seems like this file should be placed not in the `gfx` folder.

**Comment by mateoconlechuga** [comment]
I added a PR to partially fix this issue. Now I get the error:

    ld.fasmg [758] macro ? [634] macro handle [5] macro parse [300] obj/gfx/PKMNSD4.src [465]:
	XREF _pokeball_tiles_compressed:ROM
    macro ? [6] macro XREF [3] macro ? [1]:
	. def
    Processed: . := global._pokeball_tiles_compressed
    Error: symbol '_pokeball_tiles_compressed' is undefined or out of scope.

**Comment by KellerWheat** [comment]
I changed the pokeballs from a tilemap to regular sprites and the error no longer occurs.
